[2023-02-09T07:58:35.043+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: crawler-dag1.bash_command manual__2023-02-09T07:58:34.445384+00:00 [queued]>
[2023-02-09T07:58:35.052+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: crawler-dag1.bash_command manual__2023-02-09T07:58:34.445384+00:00 [queued]>
[2023-02-09T07:58:35.052+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T07:58:35.052+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-02-09T07:58:35.052+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T07:58:35.065+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): bash_command> on 2023-02-09 07:58:34.445384+00:00
[2023-02-09T07:58:35.070+0000] {standard_task_runner.py:55} INFO - Started process 1786 to run task
[2023-02-09T07:58:35.073+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crawler-dag1', 'bash_command', 'manual__2023-02-09T07:58:34.445384+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/crawler-dag.py', '--cfg-path', '/tmp/tmp3ubutsrt']
[2023-02-09T07:58:35.073+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask bash_command
[2023-02-09T07:58:35.119+0000] {task_command.py:389} INFO - Running <TaskInstance: crawler-dag1.bash_command manual__2023-02-09T07:58:34.445384+00:00 [running]> on host 9fd6eb33fd9d
[2023-02-09T07:58:35.179+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=crawler-dag1
AIRFLOW_CTX_TASK_ID=bash_command
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T07:58:34.445384+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-09T07:58:34.445384+00:00
[2023-02-09T07:58:35.179+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-09T07:58:35.180+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'ls ./../crawler/']
[2023-02-09T07:58:35.191+0000] {subprocess.py:86} INFO - Output:
[2023-02-09T07:58:35.193+0000] {subprocess.py:93} INFO - ls: cannot access './../crawler/': No such file or directory
[2023-02-09T07:58:35.193+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-09T07:58:35.202+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-09T07:58:35.205+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=crawler-dag1, task_id=bash_command, execution_date=20230209T075834, start_date=20230209T075835, end_date=20230209T075835
[2023-02-09T07:58:35.216+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task bash_command (Bash command failed. The command returned a non-zero exit code 2.; 1786)
[2023-02-09T07:58:35.244+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-09T07:58:35.298+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
